import { type NextPage } from "next";
import Head from "next/head";
import Image from 'next/image';
import { SignInButton, useUser } from '@clerk/nextjs';
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

import { type RouterOutputs, api } from "~/utils/api";
import { LoadingPage } from '~/components/loading';

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className='flex gap-3 w-full'>
      <Image
        src={user.profileImageUrl}
        alt={user.fullName || 'user name'}
        className='w-14 h-14 rounded-full'
        width={56}
        height={56}
      />
      <input type="text" placeholder='Type some emojies!' className='bg-transparent grow outline-none' />
    </div>
  );
}

type PostWithUser = RouterOutputs["post"]["getAll"][number]
const PostView = (props: PostWithUser) => {
  const { author, post } = props;

  return (
    <div key={post.id} className='p-4 border-b border-slate-400 flex gap-3'>
      <Image
        src={author.profileImageUrl}
        alt={`${author.username}'s profile picture`}
        className='w-14 h-14 rounded-full'
        width={56}
        height={56}
      />
      <div className='flex flex-col'>
        <div className='flex text-slate-300 gap-1'>
          <span>{`@${author.username}`}</span>
          <span className='font-thin'>{`${String.fromCharCode(183)} ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  )
}

const Feed = () => {
  const { data, isLoading: postLoading } = api.post.getAll.useQuery();

  if (postLoading) return (<LoadingPage />);

  return (
    <div className='flex flex-col'>
      {!data
        ? <div>No posts</div>
        : data.map((fullPost) => (
          <PostView key={fullPost.post.id} {...fullPost} />
        ))}
    </div>
  )
}

const Home: NextPage = () => {
  const { isSignedIn, isLoaded: userLoaded } = useUser();

  // Start fetching asap
  api.post.getAll.useQuery();

  if (!userLoaded) return (<div />);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className='h-full w-full md:max-w-2xl border-x border-slate-400'>
          <div className='border-b border-slate-400 flex p-4'>
            {!isSignedIn ? (
              <div className='flex justify-center'><SignInButton /></div>) : (
              <CreatePostWizard />
              // <div className='flex justify-center'><SignOutButton /></div>
            )}
          </div>

          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
